version: '3.8'

services:
  db:
    image: postgres:14
    container_name: neopostgres
    environment:
      POSTGRES_DB: NeoStore
      POSTGRES_USER: neouser
      POSTGRES_PASSWORD: neopassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
